---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # ------------------ BASE ------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: (^.github/dependabot.yml |^skaffold)
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "150", --preserve-quotes]
        exclude: (^.github/dependabot.yml |^skaffold)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.0
    hooks:
      - id: markdownlint
        args: [--ignore, node_modules, --ignore, src, --fix, --disable, MD013]
  # ------------------ TERRAFORM ------------------
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      - id: terraform_tflint
      - id: terraform_tfsec
  # # ------------------ OPS ------------------
  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  #   rev: 3.0.0
  #   hooks:
  #     - id: shellcheck
  #     - id: shfmt
  # - repo: https://github.com/AleksaC/hadolint-py
  #   rev: v1.19.0
  #   hooks:
  #     - id: hadolint
  #       args:
  #         - --ignore
  #         - DL3025
  #         - --ignore
  #         - DL3018
  #         - --ignore
  #         - DL3027
  # # ------------------ PYTHON ------------------
  # - repo: https://github.com/psf/black
  #   rev: 22.3.0
  #   hooks:
  #     - id: black
  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v2.6.0
  #   hooks:
  #     - id: reorder-python-imports
  # - repo: https://github.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       args:
  #         - --max-line-length=200
  #         - --ignore=E266,W503,E731,E722,E203,E741,W504,W605,E402
  #       additional_dependencies:
  #         - flake8-builtins
  #         - flake8-bugbear
  #       exclude: table_definitions/model.py$
  # - repo: https://github.com/myint/autoflake
  #   rev: v1.4
  #   hooks:
  #     - id: autoflake
  #       args:
  #         - --in-place
  #         - --remove-all-unused-imports
  #         - --remove-unused-variable
  # - repo: https://github.com/PyCQA/bandit
  #   rev: "1.7.4"
  #   hooks:
  #     - id: bandit
  #       # exclude: (load_tables_pyspark.py$|tests/unittests/.*.py|tests/integrations/.*.py)
  # # ------------------ jupyter ------------------
  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.1.0
  #   hooks:
  #     - id: nbqa-black
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.5.0
  #   hooks:
  #     - id: nbstripout
  # # ------------------ sql ------------------
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 1.3.2
  #   hooks:
  #     - id: sqlfluff-lint
  #     - id: sqlfluff-fix
